### ISSUE TITLE
Favorite Icon Exercise Issue

### ISSUE THREAD

**Issue by pram0dm** [mosh-hamedani/angular2-course#10]
In the Favorite icon exercise, I've set up a method for the click method. However, Chrome throws an error stating that glyphicons do not have such a method called click. Could someone kindly let me know what's the cause?

`import {Component} from 'angular2/core';

@Component({
    selector: 'favorite',
    template: 
        <i
            class="glyphicon"
            [class.glyphicon-star] = "isFavorite"
            [class.glyphicon-star-empty] = "!isFavorite"
            (click)="onClick()">
        </i>
})

export class FavoriteComponent {
    isFavorite: boolean = false;
    onCLick(){
        console.log("Clicked");
       this.isFavorite = true;
    }
}`

Console Error:
`Error during evaluation of "click"
TypeError: l_context.onClick is not a function`

Attached is the console error window error and the code

![image](https://cloud.githubusercontent.com/assets/26511587/24091176/6eae38b2-0d57-11e7-9b76-49d1198f9710.png)
![image](https://cloud.githubusercontent.com/assets/26511587/24091180/76653470-0d57-11e7-841c-48709b33e589.png)

**Comment by pram0dm** [comment]
Had a capital **L** set in the onClick method. Essentially, the names of the method did not match.

**Comment by BKD471** [comment]
how did u use the html?.pls send me the code for html
