### ISSUE TITLE
typings ERR! deprecated The "ambient" flag is deprecated. Please use "global" instead

### ISSUE THREAD

**Issue by Ayyappa-amara** [mosh-hamedani/angular2-course#9]
typings install underscore --ambient
typings ERR! deprecated The "ambient" flag is deprecated. Please use "global" instead

then when i enter with global i got list of errors. -->
C:\Users\ayyappa.amara\Documents\typrscript\demo>typings install underscore --global
typings ERR! message Unable to find "underscore" ("npm") in the registry.
typings ERR! message However, we found "underscore" for 1 other source: "dt"
typings ERR! message You can install these using the "source" option.
typings ERR! message We could use your help adding these typings to the registry: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/npm/underscore/versions/latest responded with 404, expected it to equal 200
typings ERR!
typings ERR! cwd C:\Users\ayyappa.amara.EFFONETECH\Documents\typrscript\demo
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ayyappa.amara.EFFONETECH\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install" "underscore" "--global"
typings ERR! node -v v4.5.0
typings ERR! typings -v 2.1.0
typings ERR!
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

please tell me the solution

**Comment by Ayyappa-amara** [comment]
here is the solution

typings install dt~underscore --global --save

we will not see any more errors

**Comment by Kdilshan** [comment]
can use this with ionic 3 ??
